### ISSUE TITLE
Changing background colors

### ISSUE THREAD

**Issue by nitorrep** [caco3/MeteoSwiss-Forecast#14]
Hi !
I just discovered your work and it's awesome.
I try to change the background color of the graph (when in dark mode, to black) and so far I'm not able to do it.
If you could indicate me how to do it that would be nice
FYI, I run the docker image

**Comment by caco3** [comment]
@nitorrep Thanks for your feedback!

I think you are looking for this: [meteoswissForecast.py#L468](https://github.com/caco3/MeteoSwiss-Forecast/blob/master/meteoswissForecast.py#L468)

**Comment by nitorrep** [comment]
Thank you, I was able to make the change that I wanted !
